UKGovernmentBEIS/energy-label-service

src/main/java/uk/co/fivium/els/categories/internetlabelling/model/InternetLabelOrientation.java, src/main/java/uk/co/fivium/els/categories/internetlabelling/model/InternetLabellingForm.java, src/main/resources/templates/govuk/radio.ftl
User testing showed that some of the internet labeling prompts were confusing and they weren't sure what selecting 'Pointing left' or 'Pointing right' would do, so we agreed to change the prompts and add small example images in each option:
Using SVG to ensure it looks sharp at all zoom levels, and using currentColor in the SVG to ensure it picks up user agent changes to the text color for accessibility (tested in Windows high contrast mode with IE and Firefox custom colours):
I've used inline styles on the SVGs as we don't currently have an app stylesheet and I didn't want to introduce an extra HTTP request just for this. I'll move the styling into an app stylesheet if we end up needing one later on.
=> Change internet labelling orientation/format prompts and add example images for orientation

gulpfile.js, package-lock.json, package.json
This fixes the 2 security vulnerabilities reported by `npm audit`.
Updating Gulp from 3 to 4 requires minor syntax changes to the gulpfile.
=> Update gulp. Fixes vulns in tar and fstream packages.

src/main/resources/templates/staticContent/accessibilityStatement.ftl
Changed because the accessibility statement only applies to pages on create-energy-label.service.gov.uk. The start page is on the main GOV.UK domain so isn't covered by this statement
=> Change service URL from gov.uk start page to .service.gov.uk domain

src/main/java/uk/gov/beis/els/mvc/FormAnnotationHandlerInterceptor.java, src/main/resources/templates/form.ftl, src/main/resources/templates/govuk/textInput.ftl
Also disables the browser based HTML5 form validation (which tries to validate numeric input types) as it looks awful in Firefox. GDS also do this on the design-system.
=> Automatically set HTML input field type as 'number' for numeric fields

src/main/java/uk/gov/beis/els/service/TemplatePopulator.java, src/main/resources/labels/html-wrapper.html
I've set an `id` on `title` rather than using `getElementsByTag` as by this point there are two title tags, one in the `head` and one inside the SVG. `id` on `title` is valid in HTML5
=> Set HTML title so generated label PDF has a title

src/main/resources/templates/layout.ftl
I've grepped for other `/assets/govuk-frontend` paths and this looks like the only one missing the trailing `/govuk`
=> Fix broken path to Opengraph image

src/main/java/uk/gov/beis/els/categories/dishwashers/service/DishwashersService.java, src/main/java/uk/gov/beis/els/categories/refrigeratingappliances/service/RefrigeratingAppliancesService.java, src/main/java/uk/gov/beis/els/categories/refrigeratorsdirectsales/model/BeverageCoolersForm.java, src/main/java/uk/gov/beis/els/categories/refrigeratorsdirectsales/model/DisplayCabinetsForm.java, src/main/java/uk/gov/beis/els/categories/refrigeratorsdirectsales/model/IceCreamFreezersForm.java, src/main/java/uk/gov/beis/els/categories/refrigeratorsdirectsales/model/VendingMachinesForm.java, src/main/java/uk/gov/beis/els/categories/refrigeratorsdirectsales/service/RefrigeratorsDirectSalesService.java, src/main/java/uk/gov/beis/els/categories/televisions/service/TelevisionsService.java, src/main/java/uk/gov/beis/els/categories/washingmachines/model/WasherDryerForm.java, src/main/java/uk/gov/beis/els/categories/washingmachines/service/WashingMachinesService.java, src/main/resources/labels/dishwashers/dishwashers-2021.svg, src/main/resources/labels/household-refrigerating-appliances/household-refrigerating-appliances-2021.svg, src/main/resources/labels/household-refrigerating-appliances/wine-storage-appliances-2021.svg, src/main/resources/labels/refrigerators-direct-sales/commercial-refrigeration-beverage.svg, src/main/resources/labels/refrigerators-direct-sales/ice-cream-freezers.svg, src/main/resources/labels/refrigerators-direct-sales/refrigerators-direct-sales.svg, src/main/resources/labels/televisions-electronic-displays/electronic-displays-2021.svg, src/main/resources/labels/washing-machines/washer-dryers-2021.svg, src/main/resources/labels/washing-machines/washing-machines-2021.svg
There was enough room in most templates to add a second line, so the rescaled labels can handle the same number of characters as the old labels. The light sources labels have no room for a second line but I've tested with representative 20-character strings and they just about fit. When the old labels are retired for these categories we can bump up the number of allowed characters.
=> Enable multline text for supplier and model on rescaled labels (except light sources)

src/main/java/uk/gov/beis/els/mvc/FormAnnotationHandlerInterceptor.java, src/main/resources/templates/layout.ftl
Other uses of `labelMode` occur with the context of a form so do not need the `has_content` check
=> Revert change to labelMode model attribute

src/main/java/uk/gov/beis/els/categories/lamps/controller/LampsController.java, src/main/java/uk/gov/beis/els/categories/lamps/model/LampsCategory.java, src/main/java/uk/gov/beis/els/categories/lamps/model/LampsForm.java, src/main/java/uk/gov/beis/els/categories/lamps/model/validation/LampsFormSequenceProvider.java, src/main/java/uk/gov/beis/els/model/ProductCategory.java, src/main/java/uk/gov/beis/els/model/ProductMetadata.java, src/main/resources/templates/categories/lamps/lamps.ftl
Removed the option to create rescaled Light Sources labels until it's confirmed that these will be introduced in the UK. These are the minimum changes to get the forms looking how they did before - templates etc are still there, hopefully we'll be able to just revert this change to when we need the form changes again.
=> Remove rescaled labels from Lamps forms

package-lock.json, package.json, src/main/resources/templates/govuk/button.ftl
Non-breaking release so no changes were needed in the app
Visible changes are minimal - I think limited to the secondary text grey being slightly darker and the border on error inputs being the same size as normal inputs
Before:
After:
=> Update govuk-frontend to 3.10.0

src/main/java/uk/gov/beis/els/categories/lamps/model/LampsForm.java, src/main/java/uk/gov/beis/els/categories/lamps/model/LampsFormNoSupplierModel.java
Tested across all relevant templates (old, new, small, regular, B&W/colour variants) with 9999 as input
=> Update kWh limit from 3 digits to 4

src/main/java/uk/gov/beis/els/api/categories/rangehoods/RangeHoodsApiController.java, src/main/java/uk/gov/beis/els/api/categories/rangehoods/RangeHoodsInternetLabelApiForm.java, src/main/java/uk/gov/beis/els/api/common/ApiValuesFromLegislationCategory.java, src/main/java/uk/gov/beis/els/api/openapi/OpenApiPropertyCustomiser.java, src/main/java/uk/gov/beis/els/categories/rangehoods/controller/RangeHoodsController.java, src/main/java/uk/gov/beis/els/categories/rangehoods/model/RangeHoodsForm.java, src/main/java/uk/gov/beis/els/categories/rangehoods/service/RangeHoodsService.java
Added Range hood API points
- Updated `OpenApiPropertyCustomiser` to take in the secondary `RatingRange` from the current legislation
- Currently `processLegislationCategoryValues` tries to get the rating ranges from a legislationCategory's primary rating range by default
- Added `RangeHoodsApiController` and `RangeHoodsInternetLabelApiForm`
- Updated `RangeHoodsForm`
=> ELG-14 APIs for range hoods

src/main/java/uk/gov/beis/els/api/categories/airconditioners/AirConditionersApiController.java, src/main/java/uk/gov/beis/els/api/categories/dishwashers/DishwashersApiController.java, src/main/java/uk/gov/beis/els/api/categories/domesticovens/DomesticOvensApiController.java, src/main/java/uk/gov/beis/els/api/categories/localspaceheaters/LocalSpaceHeatersApiController.java, src/main/java/uk/gov/beis/els/api/categories/prorefrigeratedcabinets/ProRefrigeratedCabinetsApiController.java, src/main/java/uk/gov/beis/els/api/categories/rangehoods/RangeHoodsApiController.java, src/main/java/uk/gov/beis/els/api/categories/refrigeratingappliances/RefrigeratingAppliancesApiController.java, src/main/java/uk/gov/beis/els/api/categories/refrigeratordirectsales/RefrigeratorsDirectSalesApiController.java, src/main/java/uk/gov/beis/els/api/categories/solidfuelboilers/SolidFuelBoilersApiController.java, src/main/java/uk/gov/beis/els/api/categories/televisions/TelevisionsApiController.java, src/main/java/uk/gov/beis/els/api/categories/tumbledryers/TumbleDryerApiController.java, src/main/java/uk/gov/beis/els/api/categories/ventilationunits/VentilationUnitsApiController.java, src/main/java/uk/gov/beis/els/api/categories/washingmachines/WashingMachinesApiController.java, src/main/java/uk/gov/beis/els/api/common/ApiDocumentationController.java, src/main/resources/scss/components/_code.scss, src/main/resources/scss/components/_sub-navigation.scss, src/main/resources/scss/main.scss, src/main/resources/templates/apidocumentation/apiDocumentationForTag.ftl, src/main/resources/templates/apidocumentation/apiDocumentationNav.ftl, src/main/resources/templates/apidocumentation/apiDocumentationStartPage.ftl, src/main/resources/templates/fds/subNavigation.ftl, src/main/resources/templates/govuk/accordion.ftl, src/main/resources/templates/govuk/footer.ftl, src/main/resources/templates/layout.ftl, src/test/java/uk/gov/beis/els/ControllerSmokeTest.java
Still WIP - whoever picks up the implementation will need to:
- update the URL for the OpenAPI doco in the 'Testing' section and in the heading of each product category ("You can import...")
- update the rate limit in the 'rate limits' section ("are rate limited to...")
- Show real base path on each endpoints page ("The base URL for all paths is...")
- Show real path for each endpoint
- Show real schema properties for each endpoint
We'll need to update the email signup URL when that decision has been made
=> API doco design and homepage content

src/main/resources/templates/common.ftl
I've used the warning text pattern rather than inset text as it's a bit more important that they read it - on normal labels we just put what they give us on the label, but on these screens we're doing calculations that ultimately, legally, they're responsible for the accuracy of.
=> Add disclaimer text to package calculators

src/main/java/uk/gov/beis/els/renderer/PdfRenderer.java, src/main/java/uk/gov/beis/els/service/DocumentRendererService.java, src/test/java/uk/gov/beis/els/service/DocumentRendererServiceTest.java
You can now pass a List of `ProcessedEnergyLabelDocument`s to the renderer and the docs will be combined into a single PDF, as required for the combination heaters fiche.
=> Add support for multiple HTML documents in a single PDF

src/main/java/uk/gov/beis/els/api/common/BaseInternetLabelApiForm.java, src/main/java/uk/gov/beis/els/api/common/RescaledInternetLabelApiForm.java, src/main/java/uk/gov/beis/els/api/openapi/OpenApiPropertyCustomiser.java, src/main/java/uk/gov/beis/els/categories/internetlabelling/service/InternetLabelService.java, src/test/java/uk/gov/beis/els/api/common/ApiValuesFromLegislationCategoryValidatorTest.java
Ensure API `validationErrors` object is returned for internet label schema errors. 
Update doco example value for string types.
=> Testing feedback changes

.github/workflows/build.yml, src/main/resources/application.properties, src/main/resources/scss/helpers/_typography.scss, src/main/resources/scss/main.scss, src/main/resources/templates/apidocumentation/apiDocumentationNav.ftl, src/main/resources/templates/apidocumentation/apiDocumentationStartPage.ftl
Added the paragraph to direct people to the endpoints in the menu, and updated the OpenAPI spec URL to make the filename more descriptive. `download` attributes added to OpenAPI links to force a file download rather than opening the JSON in the browser.
=> New 'Endpoints' doco section and update openapi url

src/main/java/uk/gov/beis/els/categories/tumbledryers/model/TumbleDryersForm.java
Have tested with `88.8` and it fits fine in the template with room to spare.
=> Increase tumble dryer rated capacity

src/main/java/uk/gov/beis/els/renderer/JpegRenderer.java, src/main/java/uk/gov/beis/els/renderer/PngRenderer.java, src/main/java/uk/gov/beis/els/renderer/Renderer.java, src/main/java/uk/gov/beis/els/util/RendererUtils.java, src/main/java/uk/gov/beis/els/util/TemplateUtils.java, src/main/resources/fiches/space-heaters/boilerSpaceHeaterPackages.svg, src/main/resources/fiches/space-heaters/cogenerationSpaceHeaterPackages.svg, src/main/resources/fiches/space-heaters/heatPumpSpaceHeaterPackages.svg, src/main/resources/fiches/space-heaters/lowTemperatureHeatPumpSpaceHeaterPackages.svg, src/main/resources/fiches/water-heaters/packages-of-water-heater-and-solar-device-fiche.svg, src/main/resources/labels/html-wrapper.html, src/main/resources/labels/internet-labelling/internet-labelling-left.svg, src/main/resources/labels/internet-labelling/internet-labelling-rescaled-bw-left.svg, src/main/resources/labels/internet-labelling/internet-labelling-rescaled-bw-right.svg, src/main/resources/labels/internet-labelling/internet-labelling-rescaled-left.svg, src/main/resources/labels/internet-labelling/internet-labelling-rescaled-right.svg, src/main/resources/labels/internet-labelling/internet-labelling-right.svg, src/test/java/uk/gov/beis/els/service/DocumentRendererServiceTest.java
Implement collation of multiple SVGs into a single PNG or JPEG. This is required for image version of the fiche.
This can't currently be tested though the screens, that will be added next but didn't want to bloat out this PR massively.
All rasterisation is done at 300 DPI. Fiche SVGs have been sized down to 1/2 A4 as discussed.
=> Add support for PNG/JPEG collation

src/main/java/uk/gov/beis/els/categories/lamps/service/LampsService.java, src/main/java/uk/gov/beis/els/categories/spaceheaters/service/SpaceHeatersService.java, src/main/java/uk/gov/beis/els/categories/waterheaters/service/WaterHeatersService.java, src/test/java/uk/gov/beis/els/categories/spaceheaters/service/SpaceHeatersServiceTest.java
- Fix output format and GA ID not getting applied in some package calculator forms
- Fix some lamps API forms not using requested output format
=> Pass through output format and GA ID in package calculator forms

src/main/resources/public/assets/scripts/cookieControl.js
The decline consent script was trying to push preferences to the Google tag in all cases, but this should only happen if they've previously granted consent for analytics - the GA `dataLayer` won't exist otherwise
=> Fix error when declining analytics cookies
